from typing import Protocol

from lesphinx.game.models import GameSession


class SessionStore(Protocol):
    def get(self, session_id: str) -> GameSession | None: ...
    def save(self, session: GameSession) -> None: ...
    def delete(self, session_id: str) -> None: ...


class AudioBlobStore(Protocol):
    def put(self, audio_id: str, data: bytes, content_type: str) -> None: ...
    def get(self, audio_id: str) -> tuple[bytes, str] | None: ...
